# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

    lane :production_firebase do
    firebase_app_distribution(
      android_artifact_path: "./app/build/outputs/apk/release/app-release.apk",
      android_artifact_type: "APK",
      app:"1:8341685357:android:9b4bec9be41a41702eeb64",
      groups: "jollibee-tester-group",
      firebase_cli_token: "1//0e83pe9yntcLHCgYIARAAGA4SNwF-L9Ir1uANafBfTbf83v47oXcDKkJyvgjtUZQR8ie8l9r1aF6ZWaD52pces0tPt0TTCJAERN0"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
